-- MySQL Script generated by MySQL Workbench
-- Wed Sep 22 16:06:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_TiVi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_TiVi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_TiVi` DEFAULT CHARACTER SET utf8 ;
USE `database_TiVi` ;

-- -----------------------------------------------------
-- Table `database_TiVi`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_TiVi`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(20) NULL,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(1) NOT NULL DEFAULT 'E',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_cliente_UNIQUE` (`cedula` ASC) VISIBLE,
  UNIQUE INDEX `email_cliente_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefono_cliente_UNIQUE` (`telefono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_TiVi`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_TiVi`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(1) NOT NULL DEFAULT 'E',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_usuario_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `cedula_usuario_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_TiVi`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_TiVi`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ivaventa` DOUBLE NOT NULL,
  `total_venta` DOUBLE NOT NULL,
  `valor_venta` DOUBLE NOT NULL,
  `usuarios_id` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ventas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_ventas_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `database_TiVi`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `database_TiVi`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_TiVi`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_TiVi`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(1) NOT NULL DEFAULT 'E',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `telefono_prov_UNIQUE` (`telefono` ASC) VISIBLE,
  UNIQUE INDEX `nit_prov_UNIQUE` (`nit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_TiVi`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_TiVi`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ivacompra` DOUBLE NOT NULL,
  `producto` VARCHAR(20) NOT NULL,
  `precio_compra` VARCHAR(20) NOT NULL,
  `precio_venta` VARCHAR(20) NOT NULL,
  `proveedores_id` INT NOT NULL,
  `estado` VARCHAR(1) NOT NULL DEFAULT 'E',
  PRIMARY KEY (`id`),
  INDEX `fk_productos_proveedores1_idx` (`proveedores_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `database_TiVi`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_TiVi`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_TiVi`.`detalle_ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_detalle_venta` VARCHAR(45) NOT NULL,
  `cantidad_producto` VARCHAR(20) NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  `valor_venta` DOUBLE NOT NULL,
  `valoriva` DOUBLE NOT NULL,
  `ventas_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_detalle_venta_UNIQUE` (`cod_detalle_venta` ASC) VISIBLE,
  UNIQUE INDEX `id_detalle_venta_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_detalle_ventas_ventas1_idx` (`ventas_id` ASC) VISIBLE,
  INDEX `fk_detalle_ventas_productos1_idx` (`productos_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_ventas_ventas1`
    FOREIGN KEY (`ventas_id`)
    REFERENCES `database_TiVi`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ventas_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `database_TiVi`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
